spring:
  application:
    name: cineverse-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cineverse}
    username: ${DB_USERNAME:cineverse}
    password: ${DB_PASSWORD:cineverse_local_pw}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:zTg5rDpCit8OH46ijGWJCwaBv8UsFPvlZyryBAEAVH8=}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
